### ISSUE TITLE
Add a table self association example.

### ISSUE THREAD

**Issue by dongfengweixiao** [jonra1993/fastapi-alembic-sqlmodel-async#32]
RT, 
In the near future, I will add the following data tables:
``` python
class HeroComment:
  id:
  hero_id:
  user_id:
  content:
  parent_id: -> point to other HeroComment
```

But before that, I want to discuss the problem of API path. Which of the following two forms is more appropriate?

- /comment/hero
- /hero/{hero_id}/comment

**Comment by jonra1993** [comment]
Hello, @dongfengweixiao I think the idea is to add a comment on a hero and also be able to create thread comments over any comment, is that the case? if not what is the purpose of the parent_id? In my opinion, the second one fits better "/hero/{hero_id}/comment" due to the model domain still being related to Hero. I believe the first one would be better if you create a class Comment and use a link table to connect Hero with Comment.

**Comment by jonra1993** [comment]
Maybe, but I do not think it is insecure due to it is just hero_id and it is not sensitive information like could be a user_id, email, password, or access and refresh tokens. What do you think?
