### ISSUE TITLE
asyncpg 0.25.0 install fail on Windows with python 3.11.

### ISSUE THREAD

**Issue by dongfengweixiao** [jonra1993/fastapi-alembic-sqlmodel-async#33]
RT
asyncpg version need update to 0.27.0.

BTW：How to minimize changes to the lock file after dependency upgrade?

**Comment by jonra1993** [comment]
Hello @dongfengweixiao you can use _poetry add asyncpg@latest_ on poetry folder to update a package to its latest version. Despite the fact that python 3.11 is really new version I am not sure if all packages are compatible or if python 3.11 is a good idea for production systems not by python but because of other libs. Currently, I had problems with other projects migrating to python 3.10 due to libraries compatibilities.

**Comment by jonra1993** [comment]
This commit https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/commit/c39efa65bc8e91fbc6028aa909e75d391912e99a upgrade libraries to their last version
