### ISSUE TITLE
Svelte instead of nextjs

### ISSUE THREAD

**Issue by bazylhorsey** [jonra1993/fastapi-alembic-sqlmodel-async#54]
I think Svelte would be a more modern and fun choice here.
It uses the actual DOM instead of the virutal DOM.
It includes Redux-like functionality out-of-the-box.
Shorter syntax. And if you need things outside of SPA (like SSR), there is SvelteKit (which to be honest I don't think is needed.)

**Comment by jonra1993** [comment]
Hello, @bazylhorsey I think that Svelte is a modern good option but I do have no expertise in Svelte I am really more comfortable and confident coding on React with Nextjs which I think is also a good modern option for a sample frontend it has already a more developed ecosystem. Something I really like about Nextjs is that it is powered by Rust which I think is also a trend in python libraries to improve speed.  I am going to meet this issue open so that in the future, we can create a Svelte version too.

**Comment by bazylhorsey** [comment]
Heya, yeah I understand completely (i love things built in rust too). One final note would be if this is just a frontend, nextjs supplies a full stack experience. If you are more comfortable in react I would go with vanilla React as you'd have no need for the backend supplies components.

**Comment by bazylhorsey** [comment]
I'd also add in that this doesn't have any blog or static type functionality based on the resources included in FastAPI. Maybe there is a direction with this I'm not understanding in your roadmap. But, a simple SPA could be deployed statically without any running service, which both React and Svelte are great options for. This could be done on nginx with port 80 via traefik based using the npm build output. Thus, I personally feel like Next.js doesn't provide much benefit for showcasing this architecture.

**Comment by jonra1993** [comment]
I agree the idea is to use Nextjs in static site mode (SPA), not server-side rendering. I think Svelte and Nextjs are just frontend frameworks they do the same at the end but I have more expertise on Nextjs than Svelte so it makes it easier to start (A Dashboard webapp with login and auth logic in our team we work with the stack of fastapi and nextjs using typescript already). But As I wrote before I am going to keep this issue open and add to todo list so we can replicate future frontend also with Svelte.

**Comment by bazylhorsey** [comment]
I don't think you understand my point.
If you understand the React syntax, then you should use React.
Nextjs is meant to be a replacement to Node+React...

**Comment by bazylhorsey** [comment]
https://www.geeksforgeeks.org/nextjs-vs-reactjs-which-one-to-choose/

**Comment by bazylhorsey** [comment]
@jonra1993 any more thoughts on this? If you're planning on continuing next.js I can close this.

**Comment by jonra1993** [comment]
Hello @bazylhorsey sorry for my late response, the plan export nextjs project into static content which does not use SSR https://beta.nextjs.org/docs/configuring/static-export it can use nginx container to serve static content but I would prefer that on dev we use the default nextjs dev server and for production deploy the static site webapp on services like s3 or by free on cloudflare pages which we already do; It is really easy to do using a GitHub action.

**Comment by bazylhorsey** [comment]
Why not just sit it in the static dir with caddy?

**Comment by jonra1993** [comment]
On production, we can take advantage of CDN of Cloudflare or S3+Cloudfront so the performance and speed of the static websites are better.

**Comment by bazylhorsey** [comment]
Okay, fair enough.
I was thinking for the use case that someone wants to run this service in a production state without use of cloud, ie on-premise.
Acknowledge this and I will close.

**Comment by jonra1993** [comment]
In such particular cases, the static assets result of build export on nextjs project "out folder" can be hosted as a static site on cady as the first option. Another option could be to configure nginx as a static server and host the assets there and a third option could be to create a node container that hosts nextjs assets (this option could take advantage of SSR). I think the first one is the most desired in the case you mention but for a cloud solution I would prefer Cloudflare or S3+Cloudfront due to the cost is almost $0 in both cases.
