### ISSUE TITLE
Questions concerning Relationship definition

### ISSUE THREAD

**Issue by klav-zhaw** [jonra1993/fastapi-alembic-sqlmodel-async#55]
Hi @jonra1993 ,
I have questions on the Relationship usage, class [Hero](https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/blob/9cc2566e5e5a38611e2d8d4e0f9d3bdc473db7bc/backend/app/app/models/hero_model.py#L14): 

Why not add a created_by_id to the HeroBase instead of Hero? Why is it Optional, or can it be required, since we always have a user that created a hero?

Where can I find information, which sa_relationship_kwargs I should use, and should there be another one to define what happens if records are deleted?

And also: why no backpopulates with the created_by relationship?
Do we really need the primaryjoin argument?

**Comment by klav-zhaw** [comment]
lazy: [medium article](https://medium.com/@ns2586/sqlalchemys-relationship-and-lazy-parameter-4a553257d9ef)

**Comment by jonra1993** [comment]
Hello, @klav-zhaw related to your questions.

1. I think it is relative to design requirements in this case create_by info, in general, is not really important information and is not required also if you think that this data can be empty on a seed. But there are other really important and required like secret_name for example. That is the logic and responding your question about why it is in Hero and not in HeroBase it is also related usually I add fields on HeroBase thinking of the most important fields that are 100% needed to create a new register in the database and also that when I create the IHeroCreate just inherit from HeroBase. Make it required will be a design requirement if your application considers that created_by_id is really important so you can move it to HeroBase and it will be required on the endpoint. Also you can see that the template create crud also accept a created_by_id [here](https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/blob/9cc2566e5e5a38611e2d8d4e0f9d3bdc473db7bc/backend/app/app/crud/base_crud.py)

2. Despite that app uses sqlmodel remember that it is just a layer above sqlalchmey so you can use everything of that just that is imported by sqlmodel. I also check the [sqlalchemy documentation](https://docs.sqlalchemy.org/en/20/orm/relationship_api.html). The advantage of sqlmodel instead of pure sqlalchemy is that you are not required to rewrite fields on schemas.

3. You can use back populate. This sample also use some but I really do not like to use it because it brings from db data that is not always required which causes delays and a decrease in speed when requesting info on an endpoint but also as it is dual backpopulate should be done in the other relation which causes two no needed request of data. I prefer just to create custom SQL queries with join when it is required. In this special case, I do not think the created_by field is really important in order it consume backend resources to get that info in each request. But maybe it can be on some statistics apis in such case just a join should be done. But if you consider this kind of data is really important your app a backpopulate is a good option.
