### ISSUE TITLE
Optional[str] vs. str | None

### ISSUE THREAD

**Issue by klav-zhaw** [jonra1993/fastapi-alembic-sqlmodel-async#56]
For example [here](https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/blob/96581ad662a3d8929baf9ec8415ae0230a2d5371/backend/app/app/models/user_model.py#L30)

Would Optional[str] have the same result?

**Comment by jonra1993** [comment]
Hello  @klav-zhaw yes sure according to new python 3.10 typing [link](https://docs.python.org/3.10/library/typing.html#typing.Optional)

Optional[X] is equivalent to X | None (or Union[X, None]), so in your question yes the last result is the same I have learned that on pydantic when you set a default value it is also optional

Like this

first_name: str                           #Required field because there is no a default value and None is not allowed
last_name: str                           #Required field because there is no a default value and None is not allowed
company_name: str = "jrtec"  # Optional field and default is 'jrtec'
age: int | None                          # Optional field and default is None
year: int = 2023                        # Optional field and default is 2023

It could be cases where you prefer a default value and others in which you can have None values on the database so str | None is a good option. If you want to learn more about of empty strings or null string on a database and its meaning you can check this [link](https://stackoverflow.com/questions/40651685/empty-string-vs-null)

**Comment by klav-zhaw** [comment]
Follow up question @jonra1993 
[ hashed_password: Optional[str] = Field(nullable=False, index=True)](https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/blob/3f1388cfb7862ecba4b8b18668212f6127b4568b/backend/app/app/models/user_model.py#L33)

How do Optional and nullable=false work together?

**Comment by jonra1993** [comment]
Hello,  @klav-zhaw I think this is wrong I am going to solve it. There could be two scenarios

1. You want to allow that user not to set a password so `hashed_password: str | None = Field(nullable=True, index=True)`
2. It is required that users have always a password so `hashed_password: str = Field(nullable=False, index=True)` is a better option

**Comment by klav-zhaw** [comment]
Follow-Up on that, @jonra1993 : I tried with option 2.. We then need to add the hashed password to the IUserCreate object somewhere in the chain. You have this config inner class with hashed_password = None
Can we add there the hashed password instead of None? Or do we need to override the Create method in the user crud? How would that look like?

**Comment by jonra1993** [comment]
Hello @vi-klaas I agree that this is a cleaner solution
