### ISSUE TITLE
SSL config for production

### ISSUE THREAD

**Issue by bazylhorsey** [jonra1993/fastapi-alembic-sqlmodel-async#59]
I see the comment in nginx for turning on SSL connections.
However, there could be code written for integrating OpenSSL.

**Comment by jonra1993** [comment]
Hi @bazylhorsey I am going to add this to todo list

**Comment by jonra1993** [comment]
Hello, @bazylhorsey I have changed traefik by caddy as a reverse proxy server. It automatically generates SSL certificates and route to 443 port on the caddy file the above lines should be uncommented to enable SSL. I chose caddy instead of treafik or nginx because it make things easier and less verbose the docker-compose configuration.
