### ISSUE TITLE
How to update many-to-many, and where celery_schedule_jobs table

### ISSUE THREAD

**Issue by joshung** [jonra1993/fastapi-alembic-sqlmodel-async#76]
Hi, thanks for your amazing work.
I have 2 questions. Please help me out
1 . I using update function on base_crud, but I can not update many-to-many table, How I can implement this one.
2.  In alembic for migration database, but I can not see "celery_schedule_jobs" table. Where is this ? 
Thanks to you so much

**Comment by webdagger** [comment]
@joshung, I think I can answer question 1. 
It would be best to make your own custom update function to handle that. Take inspiration from https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/blob/d4456ca6d28c7537537dbcad2f8e6f4a471d1101/backend/app/app/crud/user_crud.py#L65
I think the gist is you need to handle updating the relationships separately.

I can make a guess for question 2 if you are asking how the `celery_schedule_jobs` table is created, check the file `create-dbs.sql`, it is initialized in https://github.com/jonra1993/fastapi-alembic-sqlmodel-async/blob/d4456ca6d28c7537537dbcad2f8e6f4a471d1101/docker-compose-dev.yml#L28

**Comment by webdagger** [comment]
Depending on how you have set up your project. 
I assume you have some sort of `house_crud`, In your `house_crud`, you are going to overwrite the default update function or create a new one. 
```python
class HouseAndHouseTypesUpdateSchema(SqlModel):
    name: str
    types_of_house_ids: Optional[UUID] = None


   async def add_houses_to_user(
        self,
        *,
        house: House
        obj_new: HouseAndHouseTypesUpdateSchema
        db_session: AsyncSession | None = None,
    ) -> House:
        db_session = db_session or super().get_db().session
        # You should have probably checked to see that the ids are valid or you can loop here to check.
        house.house_types.extend(obj_new. types_of_house_ids)
        house.name = obj_new.name
        db_session.add(house)
        await db_session.commit()
        await db_session.refresh(house)
        return house
```
The key idea to your confusion is `obj_existing.house_types.extend(obj_new. types_of_house_ids)`, we can use this because the LinkTypeAndHouse is on the House. Beneath, SQLAlchemy knows how to manage relationships, based on how you have described it. 
Take a look at https://sqlmodel.tiangolo.com/tutorial/many-to-many/update-remove-relationships/

**Comment by joshung** [comment]
@webdagger  Thanks to you so much, now I understood.
